### ISSUE TITLE
Error using nodejs

### ISSUE THREAD

**Issue by Spo-oky** [BySlin/VideoMatrix#2]
Hi,

Thank's for this software.
I was trying to use it with node but I receive an error.

I have Windows 10
Nodejs V14.18.0

When I use yarn I receive the following message:

$ umi generate tmp
Cannot find module 'byslin-boot-view-utils/lib/plugins'
Require stack:
- C:\Programming\Decklink\VideoMatrix\.umirc.ts
- C:\Programming\Decklink\VideoMatrix\node_modules\@umijs\core\lib\Config\Config.js
- C:\Programming\Decklink\VideoMatrix\node_modules\@umijs\core\lib\index.js
- C:\Programming\Decklink\VideoMatrix\node_modules\umi\lib\ServiceWithBuiltIn.js
- C:\Programming\Decklink\VideoMatrix\node_modules\umi\lib\cli.js
- C:\Programming\Decklink\VideoMatrix\node_modules\umi\bin\umi.js
Error: Cannot find module 'byslin-boot-view-utils/lib/plugins'
Require stack:
- C:\Programming\Decklink\VideoMatrix\.umirc.ts
- C:\Programming\Decklink\VideoMatrix\node_modules\@umijs\core\lib\Config\Config.js
- C:\Programming\Decklink\VideoMatrix\node_modules\@umijs\core\lib\index.js
- C:\Programming\Decklink\VideoMatrix\node_modules\umi\lib\ServiceWithBuiltIn.js
- C:\Programming\Decklink\VideoMatrix\node_modules\umi\lib\cli.js
- C:\Programming\Decklink\VideoMatrix\node_modules\umi\bin\umi.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.mod._resolveFilename (C:\Programming\Decklink\VideoMatrix\node_modules\@umijs\bundler-webpack\lib\requireHook.js:49:28)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (C:\Programming\Decklink\VideoMatrix\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Programming\Decklink\VideoMatrix\/.umirc.ts:1:1)
    at Module._compile (C:\Programming\Decklink\VideoMatrix\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Module._compile (C:\Programming\Decklink\VideoMatrix\node_modules\@umijs\deps\compiled\babel\bundle.js:129139:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .ts] (C:\Programming\Decklink\VideoMatrix\node_modules\@umijs\deps\compiled\babel\bundle.js:129144:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Can you give me an help.
Tks

**Comment by Spo-oky** [comment]
Last version resolve it, Tks
